import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
    width: '100%',
  },
  contentWrapper: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 15,
    paddingBottom: 15,
    paddingHorizontal: 20,
    backgroundColor: '#F5F5F5',
  },
  menuButton: {
    padding: 8,
  },
  backButton: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E62130',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollView: {
    flex: 1,
    width: '100%',
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 5,
    paddingBottom: 20,
  },
  productTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#E62130',
    marginBottom: 15,
    textAlign: 'right',
  },
  eligibilityTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 15,
    textAlign: 'right',
  },
  requirementsContainer: {
    marginTop: 5,
  },
  requirementItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 0,
    paddingRight: 5,
  },
  numberContainer: {
    alignItems: 'center',
    marginLeft: 10,
    marginRight: 10,
    position: 'relative',
    minHeight: 40,
  },
  numberCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#E62130',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  numberText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  connectorLine: {
    position: 'absolute',
    width: 2.5,
    top: 30,
    left: '50%',
    marginLeft: -1.25,
    backgroundColor: '#E62130',
    height: 30,
  },
  requirementText: {
    fontSize: 16,
    color: '#000000',
    flex: 1,
    textAlign: 'right',
    lineHeight: 24,
    paddingTop: 4,
  },
  buttonsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingBottom: 25,
    paddingTop: 15,
    gap: 12,
    backgroundColor: '#F5F5F5',
    borderTopWidth: 0,
  },
  continueButton: {
    flex: 1,
    backgroundColor: '#E62130',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 50,
  },
  continueButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  cancelButton: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#E62130',
    minHeight: 50,
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#E62130',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 25,
    width: '100%',
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#2C3E50',
    marginBottom: 15,
  },
  modalMessage: {
    fontSize: 16,
    color: '#666666',
    marginBottom: 25,
    lineHeight: 24,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  modalButton: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 50,
  },
  resumeButton: {
    backgroundColor: '#E62130',
  },
  resumeButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  startNewButton: {
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#E62130',
  },
  startNewButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#E62130',
  },
});

